name = "JointChance"
uuid = "507959cc-378a-41b5-a287-a6d7388b6dc3"
authors = ["Nesrine Ouanes"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
